sudo: required

services:
  - docker

# General purpose travis instance.
# No language designation defaults to Ruby.
language: bash

before_install:
  # Dockerfile linting tool.
  # https://github.com/phase2/hadolint/hadolint
  - docker pull hadolint/hadolint
  # Double-check the version of Docker travis will use.
  - docker --version

script:
  # Lint the Dockerfile. Suppressing rules for pinning to specific dependency versions.
  - docker run --rm -i hadolint/hadolint hadolint --ignore SC2046 --ignore DL3018 --ignore DL3013 - < Dockerfile
  # Test that the image build.
  - docker build -t outrigger/gitlab-ci-workspace:tmp .
  # Version check our tools
  # If any tool is not present, the versions script will abort and the test run will fail.
  - docker run --rm outrigger/gitlab-ci-workspace:tmp /versions.sh
  # Take a closer look at the image.
  - docker image inspect outrigger/gitlab-ci-workspace:tmp
  