#!/bin/bash
YELLOW="\033[0;33m"
NORMAL="\033[0;0m"

helmVersion=v2.12.3

set -ex

for target in ${BUILD_LIST:-latest stable 18}; do
  printf "${YELLOW}Building $DOCKER_REPO:${target}...${NORMAL}\n"
  docker build -f "$DOCKERFILE_PATH" -t $DOCKER_REPO:${target} . \
    --build-arg DOCKER_ENGINE_VERSION="$target" \
    --build-arg HELM_VERSION="$helmVersion"
  printf "\n\n"
done
