#!/bin/bash
set -ex

for target in latest stable 18; do
  docker build \
      --build-arg DOCKER_ENGINE_VERSION="$target" \
      -f $DOCKERFILE_PATH \
      --tag "$DOCKER_REPO:$target" \
      .
done
