#!/bin/bash
set -ex

for target in latest stable 18; do
  docker image build \
      --build-arg DOCKER_ENGINE_VERSION="$target" \
      --tag "$DOCKER_REPO:$target" \
      --target "$target" \
      .
done
