#!/bin/bash
YELLOW="\033[0;33m"
NORMAL="\033[0;0m"

set -ex

for target in latest stable 18; do
  printf "${YELLOW}Pushing $DOCKER_REPO:${target}...${NORMAL}\n"
  docker push "$DOCKER_REPO:$target"
  printf "\n\n"
done
